name: prod-cluster
repo_url: https://github.com/gouthamyadavganta/mlops-anomaly-detection.git

aws_region: us-east-1
terraform_state: https://raw.githubusercontent.com/hashicorp/terraform-aws-consul/master/terraform.tfstate.example
kubeconfig: ~/.kube/config
helm_namespaces: ["default", "monitoring"]

ci_platform: github
github_repo: gouthamyadavganta/mlops-anomaly-detection
github_token: ${GITHUB_TOKEN}

docker_images:
  - name: gantagouthamyadav/inference-api
    tags:
      - latest
      - a842f7f
      - 272cda5

modules:
  - terraform
  - kubernetes
  - helm
  - ci_cd
  - docker
  - secrets
  - cost
  - gitops

gitops:
  method: api
  test_mode: true
  argocd_server: ""
  token: ${ARGOCD_TOKEN}
  app_whitelist: []

secrets_source: env
vault_addr: https://vault.example.com
vault_token_env: VAULT_TOKEN
env_secrets:
  - GITHUB_TOKEN
  - ARGOCD_TOKEN
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
